<br>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Contact us.
                </div>
                <div class="card-body">
                    <form method="POST" action="<?=App::config('url')?>index/contact">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Enter name" required>
                        </div>
                        <?php if(isset($error['name'])) :?>
                            <h3><?php echo $error['name']?></h3>
                        <?php endif;?>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" name="email"  id="email" placeholder="Enter email" required>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div>
                        <?php if(isset($error['email'])) :?>
                            <h3><?php echo $error['email']?></h3>
                        <?php endif;?>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control" id="message" name="message" rows="6" required></textarea>
                        </div>
                        <?php if(isset($error['msg'])) :?>
                            <h3><?php echo $error['msg']?></h3>
                        <?php endif;?>
                        <div class="mx-auto">
                        <?php if(isset($msg)) :?>
                            <h3><?php echo $msg?></h3>
                        <?php endif;?>
                        <input type="submit" class="btn btn-primary text-right" value="Send"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-4">
            <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i> Address</div>
                <div class="card-body">
                    <p>Napoleonova 999</p>
                    <p>31220 Višnjevac</p>
                    <p>Hrvatska</p>
                    <p>Email : filip.janjesic@gmail.com</p>
                    <p>Tel. 0911234567</p>
                </div>
            </div>
        </div>
    </div>
</div>
