<h2 class="text-center">My products</h2>

<?php if(isset($_SESSION['thankyou'])):?>
<h1 style="color:green"><?= $_SESSION['thankyou']?></h1>
<?php endif ?>


<div class="container">
<div style="height: 600px;" class="overflow-auto container-fluid">
    <div class="row">
        <?php if(empty($products)):?>
           <h4 class="text-center"><br><?='You currently have no products purchased';?></h4> 
        <?php endif; ?>
        <?php foreach($products as $product): ?>
        <div class="col-md-4 mt-5">  
            <div class="card" style="width: 14rem;">
                <img style ="max-height:200px" class="card-img-top" src="../../public/images/<?= $product->image ?>" alt="Card image cap">
                <div class="card-body">
                    <h4 class="card-title text-center"><?= $product->title?></h4></a>
                    <p class="card-text text-center"> Author: <?= $product->author ?></p>
                </div>
                <a href="<?= App::config('url');?>index/myproducts/<?=$product->pdf?>" class="btn btn-primary btn-lg btn-block">Download</a>
            </div>
        </div>
        <?php endforeach;?>
        </div>
</div>
