<br>
  <div class="max-width-500">
  <form class="px-4 py-3" action="<?= App::config('url');?>Login/forgotPassword" method="post">
  <h2 class="text-center">Type your email</h2><hr>
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="email@example.com">
      <h5 style="color:red"></h5>
    </div>
    <h5><?= $Msg?></h5>
    <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="Check email">
  </form>
  <div class="dropdown-divider"></div>
  <a class="dropdown-item" href="<?= App::config('url');?>Login/register">New here? Create new account</a>
  <a class="dropdown-item" href="<?= App::config('url');?>Login">You already have an account? Login</a>
</div>