<br>
  <div class="max-width-500">
  <form class="px-4 py-3" action="<?= App::config('url');?>Login" method="post">
  <h2 class="text-center">LOGIN</h2><hr>
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="email" name="email" class="form-control" id="email" value = "<?= isset($_COOKIE['Cookie1/30'])? $_COOKIE['Cookie1/30']: $returnField['email'] ?>" placeholder="email@example.com">
      <h5 style="color:red"><?= $errors['email']?></h5>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" value = "<?= isset($_COOKIE['Cookie2/30'])? $_COOKIE['Cookie2/30']:'' ?>" id="password" placeholder="Password">
      <h5 style="color:red"><?= $errors['password']?></h5>
    </div>
    <div class="mb-3">
      <div class="form-check">
        <input type="checkbox" name="checkbox" class="form-check-input" id="dropdownCheck" value= "1">
        <label class="form-check-label" for="dropdownCheck">
          Remember me
        </label>
      </div>
    </div>
    <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="Sign in">
    <?php if(isset($errors['alert'])):?>
      <br>
      <h5><?=$errors['alert'] ?></h5>
    <?php endif ?>
  </form>
  <div class="dropdown-divider"></div>
  <a class="dropdown-item" href="<?= App::config('url');?>Login/register">New here? Create new account</a>
  <a class="dropdown-item" href="<?= App::config('url');?>Login/forgotPassword">Forgot password?</a>
</div>
