<br>
<div class="max-width-500">
    <div class="container">
        <form class="px-4 py-3" action="<?= App::config('url');?>login/register" method="post">
            <h2 class="text-center">CREATE ACCOUNT</h2><hr>
            <div class="mb-3">
                <div class="row">
                    <div class="col">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" name="name" class="form-control" id="name" value = "<?= $returnField['name'] ?>" placeholder="Enter your name">
                    <h5 style="color:red"><?= $errors['name']?></h5>
                    </div>
                    <div class="col">
                    <label for="lastname"  class="form-label">Lastname</label>
                    <input type="text" name="lastname" class="form-control" id="lastname" value = "<?= $returnField['lastname'] ?>" placeholder="Enter your lastname">
                    <h5 style="color:red"><?= $errors['lastname']?></h5>
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="email" value = "<?= $returnField['email'] ?>" placeholder="Your email">
                <h5 style="color:red"><?= $errors['email']?></h5>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Set password">
                <h5 style="color:red"><?= $errors['password']?></h5>
            </div>
            <div class="mb-3">
                <label for="confirmPassword" class="form-label">Confirm password</label>
                <input type="password" name="confirmPassword" class="form-control" id="confirmPassword" placeholder="Confirm password">
            </div>
            <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="Create account">
            <h5 style="color:green"><?= $succesMsg?></h5>
        </form>
    </div>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="<?= App::config('url');?>Login">You already have an account? Login</a>
</div>
</div>  
