<br>
  <div class="max-width-500">
  <form class="px-4 py-3" action="<?= App::config('url');?>Login/resetPassword/<?= $token?>" method="post">
  <h2 class="text-center">Type new password</h2><hr>
    <div class="mb-3">
      <input type="password" name="password" class="form-control" placeholder="new password">
      <h5 style="color:red"></h5>
    </div>
    <div class="mb-3">
      <input type="password" name="confirmPassword" class="form-control" placeholder="confirm password">
    </div>
    <h5 style="color:red"><?= $Errors?></h5>
  <h5 style="color:green"><?= $SuccessMsg?></h5>
    <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="Submit">
  </form>
  <div class="dropdown-divider"></div>
  <a class="dropdown-item" href="<?= App::config('url');?>Login/register">New here? Create new account</a>
  <a class="dropdown-item" href="<?= App::config('url');?>Login">You already have an account? Login</a>
</div>
