<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?= App::config('siteTitle'); ?></title>
<meta property="og:title" content="<?= App::config('siteTitle'); ?>" />
<meta property="og:type" content="shop" />
<meta property="og:url" content="<?= App::config('url');?>"/>
<meta property="og:image" content="<?=App::config('url')?>public/images/icon/favicon-96x96.png" />
<link rel="apple-touch-icon" sizes="36x36" href="<?=App::config('url')?>public/images/icon/apple-farm_product-36x36.png">
<link rel="apple-touch-icon" sizes="48x48" href="<?=App::config('url')?>public/images/icon/apple-farm_product-48x48.png">
<link rel="apple-touch-icon" sizes="57x57" href="<?=App::config('url')?>public/images/icon/apple-farm_product-57x57.png">
<link rel="apple-touch-icon" sizes="72x72" href="<?=App::config('url')?>public/images/icon/apple-farm_product-72x72.png">
<link rel="apple-touch-icon" sizes="77x77" href="<?=App::config('url')?>public/images/icon/apple-farm_product-77x77.png">
<link rel="apple-touch-icon" sizes="96x96" href="<?=App::config('url')?>public/images/icon/apple-farm_product-96x96.png">
<link rel="apple-touch-icon" sizes="144x144" href="<?=App::config('url')?>public/images/icon/apple-farm_product-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<?=App::config('url')?>public/images/icon/apple-farm_product-152x152.png">
<link rel="apple-touch-icon" sizes="192x192" href="<?=App::config('url')?>public/images/icon/apple-farm_product-192x192.png">
<link rel="icon" type="image/png" sizes="192x192"  href="<?=App::config('url')?>public/images/icon/android-farm_product-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?=App::config('url')?>public/images/icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="<?=App::config('url')?>public/images/icon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?=App::config('url')?>public/images/icon/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="<?= App::config('url'); ?>./public/css/bootstrap.min.css">
<link rel="stylesheet" href="<?= App::config('url'); ?>./public/css/custom.css">