<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
<div class="col-md-9">   
<a class="btn btn-danger" href="<?= App::config('url');?>AdminOrders">Back</a>
<br><br>
    <h3 style ="color:green">Transaction -<?= $orderInner[0] -> transaction_id;?></h3>
    <br>
    <!-- Shopping Cart-->
    <div class="table-responsive shopping-cart">
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th class="text-center">Price</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($orderInner as $key):?>
                    <td>
                        <div class="product-item">
                            <a class="product-thumb" href=""><img src="<?= App::config('url');?>/public/images/<?=$key->image?>" alt="Product"></a>
                            <div class="product-info">
                                <h4 class="product-title"><a href=""><?= $key->brand_name?></a></h4><span><em>Manufacturer:</em> <?= $key->manufacturer ?></span>
                            </div>
                        </div>
                    </td>
                    <td class="text-center text-lg text-medium">$<?= $key->price?></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="shopping-cart-footer">
        <div class="column text-lg">Subtotal: <span class="text-medium">$<?= $orderInner[0] -> amount;?></span></div>
    </div>
</div>
<hr>
</div>
</div>
</div>