<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
    <div class="col-md-9">  
    
        <form action="<?= App::config('url'); ?>AdminCategories/createCategories" method="post">
            <div class="form-group">
                <h4>Add new category</h4>
                <input type="text" name="name" class="form-control" placeholder="Type category name">
                <br>
                <?php if(isset($error)): ?>
                    <h5 style = "color:red"><?= $error ?></h5>
                <?php endif ?>
                <input type="submit" name="submit" class="btn btn-primary" value="Add">
                <br><br>
            </div>
        </form>

        <form action="<?= App::config('url'); ?>AdminCategories/updateCategories" method="post">
            <div class="form-group">
            <h4>Update category</h4>
                <label>Choice category</label>
                <select name="selectCategories">
                <option value="">Select</option>
                <?php if(isset($categories)): ?>
                <?php foreach ($categories as $key): ?>
                <option value="<?= $key->id ?>"><?= $key -> name?></option>
                <?php endforeach; ?>
                <?php endif; ?>
                <input type="text" name="nameUpdate" class="form-control" placeholder="New category name">
                <br>
                <?php if(isset($errorUpdate)): ?>
                    <h5 style = "color:red"><?= $errorUpdate ?></h5>
                <?php endif ?>
                <input type="submit" name="submitUpdate" class="btn btn-primary" value="Update">
                <br><br>
            </div>
        </form>
    
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">Delete category</th>
                </tr>
            </thead>
            <tbody>
                <?php if(isset($categories)): ?>
                <?php foreach ($categories as $key): ?>
                <tr>
                <td><?php echo $key-> name ?></td>
                <?php if(isset($key->products) && $key -> products != 0 ):?>
                <td><i style="color:grey" title="This category has products" class="fas fa-2x fa-trash-alt"></i></td>
                <?php else:?>
                    <td onclick="return confirm('Do you want to delete the category')"><a style="color:red"  href="<?= App::config('url');?>AdminCategories/deleteCategories/<?= $key->id ?>"><i title="delete" class="fas fa-2x fa-trash-alt"></i></a></td>
                <?php endif?>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
    </div>
</div>